"""empty message

Revision ID: 8e77e00e3dc7
Revises: 1691d50a7a25
Create Date: 2026-04-16 23:39:33.106884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e77e00e3dc7'
down_revision: Union[str, Sequence[str], None] = '1691d50a7a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=32), nullable=True))
    op.alter_column('user_profile', 'first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user_profile', 'last_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user_profile', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_profile', 'last_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('user_profile', 'first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
